[package]
name = "spine_node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { version = "0.4.1", path = "../macroquad" }
monad_quad = { path = "../monad_quad" }
rusty_spine = "0.6.1"
